### ISSUE TITLE
Audioblock is not started through mesecons further away

### ISSUE THREAD

**Issue by chrbinder** [mmmsued/mesecons_audio#2]
Hi! 

The audioblock works fine when it is powered by a button, lever, plate, etc. right next to it but not when those mesecon blocks are further away and there is a mesecons line between it.

**Comment by mmmsued** [comment]
You have to change the value of hearing distance, if you stand far away from the audioblock ...

**Comment by chrbinder** [comment]
Thanks!
I did this already. I set the hearing distance to 10 and I can hear the sound fine when manually triggering it with a switch or lever. However, just powering it through mesecon wires does not help.

**Comment by mmmsued** [comment]
I tried to reproduce the error. I tested it with minetest 5.7 as singleplayer and with a local server (Windows 10 and 11). 
Additionally I tried it with a "real" server (Debian and Minetest 5.3). In all cases it worked fine.

If you set the distance to 10, but stand 11 blocks away, you won't hear anything (even if you move closer to the sound block after activation). Try 32 as the maximum value, but stand no more than 10 blocks away. Is there still a problem?

Can you send me a copy of the world?
